# Generated by Django 6.0.1 on 2026-02-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternalTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toolName', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('isCloudBased', models.BooleanField(default=False)),
            ],
        ),
    ]
